### ISSUE TITLE
Change Request #9 Bug: User Can Log in With Wrong Username and Password Combinations 

### ISSUE THREAD

**Issue by saniluqman** [saniluqman/G1_Picasso_Inventory_System#9]
Minor errors. Bugs need to be fixed include spelling error, responsiveness, data accuracy and data security.

**Comment by farhanasafran** [comment]
Correction:
Error found in conditional if statement which used || instead of &&
![image](https://user-images.githubusercontent.com/26750252/169695567-fed06f8c-9703-4c84-bc91-205c2b2bbd19.png)
Fixed
![image](https://user-images.githubusercontent.com/26750252/169695597-879b8604-8380-4e9e-b52a-3b4939650599.png)

**Comment by farhanasafran** [comment]
CR is completed
